[package]
name = "rustpad"
version = "0.1.0"
description = "Perform Padding Oracle attacks against web services."
authors = ["Csonka Mihaly <csonka.mihaly@hotmail.com>"]
edition = "2021"

[dependencies]
clap = {version = "2.33", features = ["yaml", "color"]}
reqwest = "0.11"
anyhow = "1.0"
base64 = "0.13"
hex = "0.4"
urlencoding = "2.1"
