[package]
name = "rusty_oracle"
version = "0.1.0"
description = "Perform Padding Oracle attacks against web services."
authors = ["Csonka Mihaly <csonka.mihaly@hotmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.33", features = ["yaml", "color"]}
reqwest = "0.11.6"