[package]
name = "rustpad"
version = "0.1.0"
description = "Multi-threaded Padding Oracle attacks against any service."
authors = ["Csonka Mihaly <csonka.mihaly@hotmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "2.33", default-features = true, features = ["yaml", "wrap_help"] }
reqwest = { version = "0.11", default-features = true, features = ["blocking"] }
anyhow = "1.0"
base64 = "0.13"
hex = "0.4"
urlencoding = "2.1"
is_executable = "1.0"
rayon = "1.5"