name: rustpad
version: "1.7.3"
about: Multi-threaded Padding Oracle attacks against any service.
settings:
    - SubcommandRequired
    - VersionlessSubcommands
    - GlobalVersion
    - DisableHelpSubcommand
    - InferSubcommands
    - UnifiedHelpMessage
    - ColorAuto
    - ColoredHelp
args:
    # TODO: following should be global, such that they can be placed after subcommand specifiers. But required globals are not supported by `clap`
    # https://github.com/clap-rs/clap/issues/1546
    - oracle:
        help: Oracle to question
        long_help: "The oracle to question with forged cypher texts. This can be a URL or a shell script.

        See the subcommands `web --help` and `script --help` respectively for further help."
        short: O
        long: oracle
        takes_value: true
        required: true
        # global: true
    - block_size:
        help: Block size used by the cypher
        short: B
        long: block-size
        aliases: ["block_size"]
        possible_values: [ "8", "16" ]
        takes_value: true
        required: true
        # global: true
    - decrypt:
        help: Cypher text to decrypt
        long_help: Original cypher text, received from the target service, which is to be decrypted
        short: D
        long: decrypt
        aliases: ["cypher-text", "cypher_text", "ctext"]
        takes_value: true
        required: true
        # global: true
    - encrypt:
        help: Plain text to encrypt
        long_help: Plain text to encrypt. Encryption mode requires a cypher text to gather necessary data
        short: E
        long: encrypt
        aliases: ["plain-text", "plain_text", "ptext"]
        takes_value: true
        requires: decrypt
        # global: true
    - no_iv:
        help: Cypher text without IV
        long_help: Cypher text does not include an Initialisation Vector
        short: n
        long: no-iv
        aliases: ["no_iv", "noiv"]
        global: true
    - verbose:
        help: Increase verbosity
        long_help: Increase verbosity of logging
        short: v
        long: verbose
        multiple: true
        global: true
    - threads:
        help: Thread count
        long_help: Amount of threads in the thread pool
        short: t
        long: threads
        takes_value: true
        aliases: ["thread_count", "thread-count"]
        default_value: "64"
        global: true
    - delay:
        help: Delay between requests within a thread
        long_help: Delay between requests within a thread, in milliseconds
        long: delay
        takes_value: true
        aliases: ["thread_delay", "thread-delay"]
        default_value: "0"
        global: true
    - output:
        help: Output to file
        long_help: File path to which log output will be written
        short: o
        long: output
        aliases: ["log", "log_file", "log-file"]
        takes_value: true
        global: true
    - encoding:
        help: Specify cypher text encoding
        long_help: Specify encoding used by the oracle to encode the cypher text
        short: e
        long: encoding
        aliases: ["cypher_text_encoding", "cypher-text-encoding"]
        takes_value: true
        possible_values: [ "auto", "base64", "base64url", "hex" ]
        default_value: "auto"
        global: true
    - no_url_encode:
        help: Disable URL encoding and decoding of cypher text
        long: no-url-encode
        aliases: ["no_url_encode"]
        takes_value: false
        global: true
    - no_cache:
        help: Disable cache
        long_help: Disable reading and writing to the cache file
        long: no-cache
        aliases: ["no_cache"]
        takes_value: false
        global: true

subcommands:
    - web:
        about: Question a web-based oracle
        after_help: Indicate the cypher text's location! See `--keyword` for clarification.
        display_order: 1
        short_flag: W
        long_flag: web
        settings:
            - UnifiedHelpMessage
            - ColorAuto
            - ColoredHelp
        args:
            - data:
                help: Data to send in a POST request
                short: d
                long: data
                takes_value: true
            - header:
                help: HTTP header to send
                short: H
                long: header
                multiple: true
                number_of_values: 1
                takes_value: true
            - redirect:
                help: Follow 302 Redirects
                short: r
                long: redirect
                takes_value: false
            - insecure:
                help: Disable TLS certificate validation
                short: k
                long: insecure
                takes_value: false
            - keyword:
                help: Keyword indicating the cypher text
                long_help: Keyword indicating the location of the cypher text in the HTTP request. It is replaced by the cypher text's value at runtime
                short: K
                long: keyword
                default_value: CTEXT
                takes_value: true
            - consider_body:
                help: Consider the body during calibration
                long_help: Consider the response body and content length when determining the web oracle's response to (in)correct padding
                short: c
                long: consider-body
                aliases: ["consider_body", "consider-content", "consider_content"]
                takes_value: false
            - user_agent:
                help: User-agent to identify with
                short: A
                long: user-agent
                aliases: ["user_agent"]
                # `<version>` is replaced in config parsing to show correct version
                default_value: rustpad/<version>
                takes_value: true
            - proxy:
                help: Proxy server
                long_help: Proxy server to send web requests over. Supports HTTP(S) and SOCKS5
                short: x
                long: proxy
                aliases: ["proxy_server", "proxy-server", "proxy_url", "proxy-url"]
                takes_value: true
            - proxy_credentials:
                help: Credentials for proxy server
                long_help: "Credentials to authenticate against the proxy server with [format: <user>:<pass>]"
                long: proxy-credentials
                aliases: ["proxy_credentials"]
                takes_value: true
                requires: proxy
            - timeout:
                help: Web request timeout
                long_help: Web request timeout in seconds
                short: T
                long: timeout
                aliases: ["request_timeout", "request-timeout"]
                takes_value: true
                default_value: "10"

    - script:
        about: Question a script-based oracle
        after_help: Script must respond with exit code 0 for correct padding, and any other code otherwise. Cypher text is passed as the 1st argument.
        display_order: 2
        short_flag: S
        long_flag: script
        settings:
            - UnifiedHelpMessage
            - ColorAuto
            - ColoredHelp