name: rustpad
version: "0.1.0"
about: Multi-threaded Padding Oracle attacks against any service.
settings:
    - SubcommandRequired
    - VersionlessSubcommands
    - GlobalVersion
    - DisableHelpSubcommand
    - InferSubcommands
    - UnifiedHelpMessage
    - ColorAuto
    - ColoredHelp
args:
    # TODO: these 3 should be global, such that they can be placed after subcommand specifiers. But required globals are not supported by `clap`
    # https://github.com/clap-rs/clap/issues/1546
    - oracle:
        help: Oracle to question
        long_help: "The oracle to question with forged cypher texts. This can be a URL or a shell script.

        See the subcommands `web --help` and `script --help` respectively for further help."
        short: o
        long: oracle
        takes_value: true
        required: true
        # global: true
    - cypher_text:
        help: Original cypher text
        long_help: Original cypher text received from the target service
        aliases: ctext
        short: t
        long: cypher_text
        takes_value: true
        required: true
        # global: true
    - block_size:
        help: Block size used by the cypher
        short: b
        long: block_size
        possible_values: [ "8", "16" ]
        takes_value: true
        required: true
        # global: true
subcommands:
    - web:
        about: Question a web-based oracle
        after_help: Indicate the cypher text's location! See `--keyword` for clarification.
        display_order: 1
        short_flag: W
        long_flag: web
        settings:
            - UnifiedHelpMessage
            - ColorAuto
            - ColoredHelp
        args:
            - data:
                help: Data to send in a POST request
                short: d
                long: data
                takes_value: true
            - header:
                help: HTTP header to send
                short: H
                long: header
                multiple: true
                number_of_values: 1
                takes_value: true
            - redirect:
                help: Follow 302 Redirects
                short: r
                long: redirect
                takes_value: false
            - insecure:
                help: Disable TLS certificate validation
                short: k
                long: insecure
                takes_value: false
            - keyword:
                help: Keyword indicating the cypher text
                long_help: This keyword indicates the location of the cypher text in the HTTP request. It is replaced by the cypher text's value at runtime
                short: w
                long: keyword
                default_value: CTEXT
                takes_value: true
            - consider_body:
                help: Consider the body during calibration
                long_help: Consider the response body and content length when determining how the web oracle responds to (in)correct padding
                aliases: consider_content
                short: c
                long: consider_body
                takes_value: false

    - script:
        about: Question a script-based oracle
        after_help: Script must respond with exit code 0 for correct padding, and any other code otherwise. Cypher text is passed as the 1st argument.
        display_order: 2
        short_flag: S
        long_flag: script
        settings:
            - UnifiedHelpMessage
            - ColorAuto
            - ColoredHelp